<?php
namespace ProposalManager\fns\robots;

/**
 * Modify the generated robots.txt output to exclude proposal view URLs.
 *
 * Appends a Disallow rule targeting the `/view-proposal/` path, preventing
 * crawlers from attempting to access those URLs. This filter only applies
 * when WordPress is generating a virtual robots.txt file (i.e., when no
 * physical robots.txt exists in the web root).
 *
 * @param string $output Current robots.txt contents generated by WordPress.
 * @param bool   $public Whether the site is considered public (from
 *                       the 'blog_public' option).
 *
 * @return string Modified robots.txt output.
 */
add_filter( 'robots_txt', function( $output, $public ) {
  $output .= "\n# Block proposal views\n";
  $output .= "Disallow: /view-proposal/\n";
  return $output;
}, 10, 2 );
